apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-image
        ports:
          - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-service
          - name: WORDPRESS_DB_USER
            value: wordpressuser
          - name: WORDPRESS_DB_PASSWORD
            value: wordpresspassword
          - name: WORDPRESS_DB_NAME
            value: wordpress