# Use the official MySQL image as the base image
FROM mysql:latest

# Set up environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=wordpressuser
ENV MYSQL_PASSWORD=wordpresspassword

# Expose MySQL port
EXPOSE 3306